import type { Material, QuoteWithItems } from "@/db/schema";

export const DEMO_MATERIALS: Material[] = [
  {
    id: "demo-mat-1",
    userId: "demo",
    name: "Hoja A4 Vinilo blanco Adhesivo",
    category: "Sustrato",
    unit: "hoja",
    price: 20,
    color: "#f97316",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
  {
    id: "demo-mat-2",
    userId: "demo",
    name: "Hoja A4 Fotográfico Adhesivo",
    category: "Sustrato",
    unit: "hoja",
    price: 7,
    color: "#3b82f6",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
  {
    id: "demo-mat-3",
    userId: "demo",
    name: "Hoja A4 Laminado Brillo",
    category: "Laminado",
    unit: "hoja",
    price: 11,
    color: "#a855f7",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
];

export const DEMO_QUOTES: QuoteWithItems[] = [
  {
    id: "demo-quote-1",
    userId: "demo",
    name: "Stickers logo cliente A",
    qty: 200,
    sheetType: "A4",
    sheetW: 210,
    sheetH: 297,
    stickerW: 50,
    stickerH: 50,
    bleed: 2,
    perSheet: 15,
    sheetsNeeded: 14,
    rotated: false,
    materialCost: 434,
    markup: 50,
    totalPrice: 651,
    pricePerUnit: 3.26,
    createdAt: "2025-03-10T14:00:00",
    items: [
      {
        id: "demo-item-1a",
        quoteId: "demo-quote-1",
        materialId: "demo-mat-1",
        name: "Hoja A4 Vinilo blanco Adhesivo",
        unit: "hoja",
        unitPrice: 20,
        qty: 14,
        subtotal: 280,
      },
      {
        id: "demo-item-1b",
        quoteId: "demo-quote-1",
        materialId: "demo-mat-3",
        name: "Hoja A4 Laminado Brillo",
        unit: "hoja",
        unitPrice: 11,
        qty: 14,
        subtotal: 154,
      },
    ],
  },
  {
    id: "demo-quote-2",
    userId: "demo",
    name: "Stickers producto temporada",
    qty: 500,
    sheetType: "A3",
    sheetW: 297,
    sheetH: 420,
    stickerW: 60,
    stickerH: 40,
    bleed: 2,
    perSheet: 24,
    sheetsNeeded: 21,
    rotated: false,
    materialCost: 378,
    markup: 40,
    totalPrice: 529.2,
    pricePerUnit: 1.06,
    createdAt: "2025-03-18T09:30:00",
    items: [
      {
        id: "demo-item-2a",
        quoteId: "demo-quote-2",
        materialId: "demo-mat-2",
        name: "Hoja A4 Fotográfico Adhesivo",
        unit: "hoja",
        unitPrice: 7,
        qty: 21,
        subtotal: 147,
      },
      {
        id: "demo-item-2b",
        quoteId: "demo-quote-2",
        materialId: "demo-mat-3",
        name: "Hoja A4 Laminado Brillo",
        unit: "hoja",
        unitPrice: 11,
        qty: 21,
        subtotal: 231,
      },
    ],
  },
];
