import type { Material, QuoteWithItems } from "@/db/schema";

export const DEMO_MATERIALS: Material[] = [
  {
    id: "demo-mat-1",
    userId: "demo",
    name: "Hoja A5 Vinilo blanco Adhesivo",
    category: "Sustrato",
    unit: "hoja",
    price: 10,
    color: "#f97316",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
  {
    id: "demo-mat-2",
    userId: "demo",
    name: "Hoja A5 Fotográfico Adhesivo",
    category: "Sustrato",
    unit: "hoja",
    price: 4,
    color: "#3b82f6",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
  {
    id: "demo-mat-3",
    userId: "demo",
    name: "Hoja A5 Laminado Brillo",
    category: "Laminado",
    unit: "hoja",
    price: 6,
    color: "#a855f7",
    createdAt: "2025-01-01T00:00:00",
    updatedAt: "2025-01-01T00:00:00",
  },
];

export const DEMO_QUOTES: QuoteWithItems[] = [
  {
    id: "demo-quote-1",
    userId: "demo",
    name: "Stickers logo cliente A",
    qty: 200,
    sheetType: "A5",
    sheetW: 148,
    sheetH: 210,
    stickerW: 50,
    stickerH: 50,
    bleed: 0,
    perSheet: 8,
    sheetsNeeded: 25,
    rotated: false,
    materialCost: 400,
    markup: 50,
    totalPrice: 600,
    pricePerUnit: 3,
    createdAt: "2025-03-10T14:00:00",
    items: [
      {
        id: "demo-item-1a",
        quoteId: "demo-quote-1",
        materialId: "demo-mat-1",
        name: "Hoja A5 Vinilo blanco Adhesivo",
        unit: "hoja",
        unitPrice: 10,
        qty: 25,
        subtotal: 250,
      },
      {
        id: "demo-item-1b",
        quoteId: "demo-quote-1",
        materialId: "demo-mat-3",
        name: "Hoja A5 Laminado Brillo",
        unit: "hoja",
        unitPrice: 6,
        qty: 25,
        subtotal: 150,
      },
    ],
  },
  {
    id: "demo-quote-2",
    userId: "demo",
    name: "Stickers producto temporada",
    qty: 500,
    sheetType: "A5",
    sheetW: 148,
    sheetH: 210,
    stickerW: 40,
    stickerH: 60,
    bleed: 0,
    perSheet: 10,
    sheetsNeeded: 50,
    rotated: true,
    materialCost: 500,
    markup: 40,
    totalPrice: 700,
    pricePerUnit: 1.4,
    createdAt: "2025-03-18T09:30:00",
    items: [
      {
        id: "demo-item-2a",
        quoteId: "demo-quote-2",
        materialId: "demo-mat-2",
        name: "Hoja A5 Fotográfico Adhesivo",
        unit: "hoja",
        unitPrice: 4,
        qty: 50,
        subtotal: 200,
      },
      {
        id: "demo-item-2b",
        quoteId: "demo-quote-2",
        materialId: "demo-mat-3",
        name: "Hoja A5 Laminado Brillo",
        unit: "hoja",
        unitPrice: 6,
        qty: 50,
        subtotal: 300,
      },
    ],
  },
];
